# Generated by Django 3.2 on 2022-01-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile\\drf-cbv.jpg', upload_to='userprofile'),
        ),
    ]
